[package]
name = "crabfetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
shellexpand = "2.1.0"
colored = "2.1.0"
config = "0.14.0"
serde = "1.0.197"
